run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck # Check for unchecked errors
    - gosimple # Suggests code simplifications
    - govet # Reports suspicious constructs
    - ineffassign # Detects unused assignments
    - staticcheck # Go static analysis tool
    - typecheck # Like the front-end of a Go compiler
    - unused # Checks for unused constants, variables, functions and types

linters-settings:
  staticcheck:
    checks:
      - _SA1029
    
issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
