version: 2
project_name: gh-gong
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - arm64
      - amd64
    binary: gh-gong
    ignore:
      - goos: linux
        goarch: arm64
    flags:
      - -tags=release
    ldflags:
      - -s -w -X cmd.Version={{.Version}}
release:
  github:
    owner: Djiit
    name: gh-gong
  prerelease: auto
  mode: keep-existing
archives:
  - name_template: "{{ .ProjectName}}-{{.Os}}-{{.Arch}}"
    formats:
      - binary
changelog:
  disable: true
checksum:
  disable: true
upx:
  - enabled: true
